ARG BASE_IMAGE=python:3.7-buster
FROM ${BASE_IMAGE}

# Build args
ARG SDIST
ARG DEFAULT_ACTOR_CONTEXT=/tmp/default_actor_context
ARG PYTHON=python3
ARG SCRATCH=/mnt/ephemeral-01
ENV SCRATCH=${SCRATCH}

# Force locale to UTF-8
RUN apt-get update && \
    apt-get install -y locales locales-all && \
    apt-get clean
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

# This is a container-local directory that all UIDs can write to. It will
# of course, not survive when the container is torn down.
# Other entries in /mnt/ will be various types of persistent storage
RUN mkdir -p ${SCRATCH} && \
    chmod a+rwx ${SCRATCH} && \
    chmod g+rwxs ${SCRATCH}

# Install Reactors SDK
ADD ${SDIST} /tmp
RUN pip install --upgrade -q /tmp/reactors-*

# Add default Reactor assets
ADD src/reactor.py /reactor.py

# Add Reactor assets on build
ONBUILD ADD requirements.txt /tmp/requirements.txt
ONBUILD RUN ${PYTHON} -m pip3 install -r /tmp/requirements.txt
ONBUILD ADD reactor.py /
ONBUILD ADD config.yml /
ONBUILD ADD message.jsonschema context.jsonschema* /

CMD ["python3", "-m", "reactors.cli", "run"]

# Close out making absolutely sure that work directory is set
WORKDIR ${SCRATCH}
