FROM python:3.7

ARG SCRATCH=/mnt/ephemeral-01
ARG SDIST

ENV SCRATCH=${SCRATCH}

# Force locale to UTF-8
RUN apt-get update && \
    apt-get install -y locales locales-all && \
    apt-get clean
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

# This is a container-local directory that all UIDs can write to. It will
# of course, not survive when the container is torn down.
# Other entries in /mnt/ will be various types of persistent storage
RUN mkdir -p ${SCRATCH} && \
    chmod a+rwx ${SCRATCH} && \
    chmod g+rwxs ${SCRATCH}

RUN pip uninstall -y agavepy
ADD ${SDIST} /
ADD reactor.py /reactor.py
RUN pip install --upgrade -q /reactors-*

# Onbuild support
ONBUILD ADD requirements.txt /tmp/requirements.txt
ONBUILD RUN pip3 install -r /tmp/requirements.txt
ONBUILD ADD reactor.py /
ONBUILD ADD config.yml /
ONBUILD ADD message.jsonschema context.jsonschema* /

CMD ["python3", "-m", "reactors.cli", "run"]

# Close out making absolutely sure that work directory is set
WORKDIR ${SCRATCH}
