logger:
  client_key: ~
  host: ~
  path: ~
  port: ~
  proto: https
  uri: ~
loggly:
  customer_token: ~
  url: https://logs-01.loggly.com/inputs/{customer_token}/tag/python
logs:
  file: ~
  level: DEBUG
  token: ~
slack:
  channel: general
  webhook: ~
