logger:
  client_key: null
  host: null
  path: null
  port: null
  proto: https
  uri: null
loggly:
  customer_token: null
  url: https://logs-01.loggly.com/inputs/{customer_token}/tag/python
logs:
  file: null
  level: DEBUG
  token: null
slack:
  channel: general
  webhook: null
