---
logger:
  client_key: ~
  path: ~
  proto: https
  host: ~
  port: ~
  uri: ~
logs:
  level: DEBUG
  file: ~
  token: ~
slack:
  channel: "general"
  webhook: ~
loggly:
  customer_token: ~
  url: "https://logs-01.loggly.com/inputs/{customer_token}/tag/python"
